name = "ghostshell-registry"
main = "src/index.js"
compatibility_date = "2026-02-10"
account_id = "9f56502f4c08f85727d5137b25cc9df7"

routes = [
  { pattern = "ghostshell.host/cert/*", zone_name = "ghostshell.host" },
  { pattern = "ghostshell.host/api/*", zone_name = "ghostshell.host" },
  { pattern = "ghostshell.host/r/*", zone_name = "ghostshell.host" },
  { pattern = "ghostshell.host/p/*", zone_name = "ghostshell.host" },
  { pattern = "ghostshell.host/handoff*", zone_name = "ghostshell.host" }
]

[[d1_databases]]
binding = "DB"
database_name = "ghostshell_registry"
database_id = "574c8401-0059-4196-a13e-f75fb8a9076c"
